// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OddsScanner.Infrastructure.Persistence;

#nullable disable

namespace OddsScanner.Infrastructure.Migrations
{
    [DbContext(typeof(OddsScannerDbContext))]
    [Migration("20260102142346_AddLogo")]
    partial class AddLogo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OddsScanner.Domain.Entities.Bookmaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffiliateUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Bookmakers");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgCorners")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "avg_corners");

                    b.Property<decimal>("AvgGoals")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "avg_goals");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "away_team");

                    b.Property<string>("AwayTeamLogo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "home_team");

                    b.Property<string>("HomeTeamLogo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "home_team_logo");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "league");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "start_time");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Odd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookmakerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Selection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookmakerId");

                    b.HasIndex("MatchId");

                    b.ToTable("Odds");

                    b.HasAnnotation("Relational:JsonPropertyName", "odds");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.OddHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OddId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OddId", "RecordedAt");

                    b.ToTable("OddHistories");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Surebet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProfitPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Surebets");

                    b.HasAnnotation("Relational:JsonPropertyName", "surebets");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Match", b =>
                {
                    b.OwnsMany("OddsScanner.Domain.Entities.H2HGame", "HeadToHead", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AwayScore")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "away_score");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone")
                                .HasAnnotation("Relational:JsonPropertyName", "date");

                            b1.Property<int>("HomeScore")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "home_score");

                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Winner")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasAnnotation("Relational:JsonPropertyName", "winner");

                            b1.HasKey("Id");

                            b1.HasIndex("MatchId");

                            b1.ToTable("MatchHeadToHead", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.OwnsMany("OddsScanner.Domain.Entities.FormGame", "AwayForm", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Opponent")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasAnnotation("Relational:JsonPropertyName", "opponent");

                            b1.Property<string>("Result")
                                .IsRequired()
                                .HasMaxLength(1)
                                .HasColumnType("character varying(1)")
                                .HasAnnotation("Relational:JsonPropertyName", "result");

                            b1.HasKey("Id");

                            b1.HasIndex("MatchId");

                            b1.ToTable("MatchAwayForm", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.OwnsMany("OddsScanner.Domain.Entities.FormGame", "HomeForm", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Opponent")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasAnnotation("Relational:JsonPropertyName", "opponent");

                            b1.Property<string>("Result")
                                .IsRequired()
                                .HasMaxLength(1)
                                .HasColumnType("character varying(1)")
                                .HasAnnotation("Relational:JsonPropertyName", "result");

                            b1.HasKey("Id");

                            b1.HasIndex("MatchId");

                            b1.ToTable("MatchHomeForm", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("AwayForm");

                    b.Navigation("HeadToHead");

                    b.Navigation("HomeForm");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Odd", b =>
                {
                    b.HasOne("OddsScanner.Domain.Entities.Bookmaker", "Bookmaker")
                        .WithMany()
                        .HasForeignKey("BookmakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OddsScanner.Domain.Entities.Match", "Match")
                        .WithMany("Odds")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bookmaker");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.OddHistory", b =>
                {
                    b.HasOne("OddsScanner.Domain.Entities.Odd", "Odd")
                        .WithMany("History")
                        .HasForeignKey("OddId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odd");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Surebet", b =>
                {
                    b.HasOne("OddsScanner.Domain.Entities.Match", "Match")
                        .WithMany("Surebets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Match", b =>
                {
                    b.Navigation("Odds");

                    b.Navigation("Surebets");
                });

            modelBuilder.Entity("OddsScanner.Domain.Entities.Odd", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
