name: Backend CI (.NET)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/backend/**' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src/backend

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore OddsScanner.sln

    - name: Build
      run: dotnet build OddsScanner.sln --no-restore --configuration Release

    - name: Test
      # Roda os testes unitários
      run: dotnet test OddsScanner.sln --no-build --configuration Release --verbosity normal
